cclog("Shuffle2UI==========================================================")
--UI类,继承自ViewBase,是一个node类型的类
--Create root
local Shuffle2UI = class("Shuffle2UI", cc.load("mvc").ViewBase, function()
    root = cc.Node:create()
    root:setName("uiRoot")
    return root
end)


local function initUI()
--Create Cocos Studio UI
    local function createCocosStudioUI()
        -- using for layout to decrease count of local variables
        local layout = nil
        local localLuaFile = nil
        local innerCSD = nil
        local innerProject = nil
        local localFrame = nil
--Create scrollView
        local scrollView = ccui.ScrollView:create()
        scrollView:setInnerContainerSize({width = 768, height = 256})
        scrollView:ignoreContentAdaptWithSize(false)
        scrollView:setClippingEnabled(false)
        scrollView:setBackGroundColorType(1)
        scrollView:setBackGroundColor({r = 0, g = 0, b = 0})
        scrollView:setLayoutComponentEnabled(true)
        scrollView:setName("scrollView")
        scrollView:setTag(13)
        scrollView:setCascadeColorEnabled(true)
        scrollView:setCascadeOpacityEnabled(true)
        scrollView:setAnchorPoint(0.5000, 0.5000)
        scrollView:setPosition(480.0000, 576.0000)
        layout = ccui.LayoutComponent:bindLayoutComponent(scrollView)
        layout:setPositionPercentXEnabled(true)
        layout:setPositionPercentYEnabled(true)
        layout:setPositionPercentX(0.5000)
        layout:setPositionPercentY(0.9000)
        layout:setPercentWidthEnabled(true)
        layout:setPercentHeightEnabled(true)
        layout:setPercentWidth(0.8000)
        layout:setPercentHeight(0.2000)
        layout:setSize({width = 768.0000, height = 128.0000})
        layout:setLeftMargin(96.0000)
        layout:setRightMargin(96.0000)
        layout:setBottomMargin(512.0000)
        root:addChild(scrollView,UI_LAYERZORDER_BACKGROUND)

        --Create label_Aside
        local label_Aside = ccui.Text:create()
        label_Aside:ignoreContentAdaptWithSize(false)
        label_Aside:setFontName("fonts/simhei.ttf")
        label_Aside:setFontSize(36)
        label_Aside:setString(Aside_Shuffle["Aside_Shuffle2"])
        label_Aside:setLayoutComponentEnabled(true)
        label_Aside:setName("label_Aside")
        label_Aside:setTag(14)
        label_Aside:setCascadeColorEnabled(true)
        label_Aside:setCascadeOpacityEnabled(true)
        label_Aside:setAnchorPoint(0.5000, 0.0000)
        label_Aside:setPosition(384.0000, 0.0000)
        layout = ccui.LayoutComponent:bindLayoutComponent(label_Aside)
        layout:setPositionPercentXEnabled(true)
        layout:setPositionPercentYEnabled(true)
        layout:setPositionPercentX(0.5000)
        layout:setPercentWidthEnabled(true)
        layout:setPercentHeightEnabled(true)
        layout:setPercentWidth(1.0000)
        layout:setPercentHeight(1.0000)
        layout:setSize({width = 768.0000, height = 256.0000})
        scrollView:addChild(label_Aside)

        --Create backGround
        local backGround = ccui.Layout:create()
        backGround:ignoreContentAdaptWithSize(false)
        backGround:setBackGroundImage("Photos/TAROTBACKGROUND.jpg",0)
        backGround:setClippingEnabled(true)
        backGround:setBackGroundColorType(1)
        backGround:setBackGroundColor({r = 0, g = 0, b = 0})
        backGround:setTouchEnabled(true);
        backGround:setLayoutComponentEnabled(true)
        backGround:setName("backGround")
        backGround:setTag(15)
        backGround:setCascadeColorEnabled(true)
        backGround:setCascadeOpacityEnabled(true)
        backGround:setAnchorPoint(0.5000, 0.5000)
        backGround:setPosition(480.0000, 256.0000)
        layout = ccui.LayoutComponent:bindLayoutComponent(backGround)
        layout:setPositionPercentXEnabled(true)
        layout:setPositionPercentYEnabled(true)
        layout:setPositionPercentX(0.5000)
        layout:setPositionPercentY(0.4000)
        layout:setPercentWidthEnabled(true)
        layout:setPercentHeightEnabled(true)
        layout:setPercentWidth(0.9000)
        layout:setPercentHeight(0.9000)
        layout:setSize({width = 864.0000, height = 576.0000})
        layout:setLeftMargin(48.0000)
        layout:setRightMargin(48.0000)
        layout:setTopMargin(96.0000)
        layout:setBottomMargin(-32.0000)
        root:addChild(backGround,UI_LAYERZORDER_BACKGROUND)

        --Create menuPanel
        local menuPanel = ccui.Layout:create()
        menuPanel:ignoreContentAdaptWithSize(false)
        menuPanel:setClippingEnabled(false)
        menuPanel:setBackGroundColorType(1)
        menuPanel:setBackGroundColor({r = 0, g = 0, b = 0})
        menuPanel:setBackGroundColorOpacity(0)
        menuPanel:setLayoutComponentEnabled(true)
        menuPanel:setName("menuPanel")
        menuPanel:setTag(16)
        menuPanel:setCascadeColorEnabled(true)
        menuPanel:setCascadeOpacityEnabled(true)
        menuPanel:setAnchorPoint(0.5000, 0.0000)
        menuPanel:setPosition(480.0000, 0.0000)
        layout = ccui.LayoutComponent:bindLayoutComponent(menuPanel)
        layout:setPositionPercentXEnabled(true)
        layout:setPositionPercentX(0.5000)
        layout:setPercentWidthEnabled(true)
        layout:setPercentHeightEnabled(true)
        layout:setPercentWidth(0.8000)
        layout:setPercentHeight(0.8500)
        layout:setSize({width = 768.0000, height = 544.0000})
        layout:setLeftMargin(96.0000)
        layout:setRightMargin(96.0000)
        layout:setTopMargin(96.0000)
        root:addChild(menuPanel,UI_LAYERZORDER_MENU)

        --Create shuffleTopChooseItem
        shuffleTopChooseItem = ccui.Button:create()
        shuffleTopChooseItem:ignoreContentAdaptWithSize(false)
        shuffleTopChooseItem:loadTextureNormal("Photos/Button/3DBUTTONSMALL_NORMAL.png",0)
        shuffleTopChooseItem:loadTexturePressed("Photos/Button/3DBUTTONSMALL_SELECTED.png",0)
        shuffleTopChooseItem:loadTextureDisabled("Default/Button_Disable.png",0)
        shuffleTopChooseItem:setTitleFontName("fonts/STHUPO.TTF")
        shuffleTopChooseItem:setTitleFontSize(36)
        shuffleTopChooseItem:setTitleText(Ui_Shuffle_Button["Ui_Shuffle_Button_Top"])
        shuffleTopChooseItem:setScale9Enabled(true)
        shuffleTopChooseItem:setCapInsets({x = 15, y = 11, width = 270, height = 38})
        shuffleTopChooseItem:setLayoutComponentEnabled(true)
        shuffleTopChooseItem:setName("shuffleTopChooseItem")
        shuffleTopChooseItem:setTag(20)
        shuffleTopChooseItem:setCascadeColorEnabled(true)
        shuffleTopChooseItem:setCascadeOpacityEnabled(true)
        shuffleTopChooseItem:setPosition(691.2000, 489.6000)
        layout = ccui.LayoutComponent:bindLayoutComponent(shuffleTopChooseItem)
        layout:setPositionPercentXEnabled(true)
        layout:setPositionPercentYEnabled(true)
        layout:setPositionPercentX(0.9000)
        layout:setPositionPercentY(0.9000)
        layout:setPercentWidth(0.3906)
        layout:setPercentHeight(0.1103)
        layout:setSize({width = 300.0000, height = 60.0000})
        layout:setLeftMargin(541.2000)
        layout:setRightMargin(-73.2000)
        layout:setTopMargin(24.4000)
        layout:setBottomMargin(459.6000)
        menuPanel:addChild(shuffleTopChooseItem)

        --Create shuffleCenterChooseItem
        shuffleCenterChooseItem = ccui.Button:create()
        shuffleCenterChooseItem:ignoreContentAdaptWithSize(false)
        shuffleCenterChooseItem:loadTextureNormal("Photos/Button/3DBUTTONSMALL_NORMAL.png",0)
        shuffleCenterChooseItem:loadTexturePressed("Photos/Button/3DBUTTONSMALL_SELECTED.png",0)
        shuffleCenterChooseItem:loadTextureDisabled("Default/Button_Disable.png",0)
        shuffleCenterChooseItem:setTitleFontName("fonts/STHUPO.TTF")
        shuffleCenterChooseItem:setTitleFontSize(36)
        shuffleCenterChooseItem:setTitleText(Ui_Shuffle_Button["Ui_Shuffle_Button_Center"])
        shuffleCenterChooseItem:setScale9Enabled(true)
        shuffleCenterChooseItem:setCapInsets({x = 15, y = 11, width = 270, height = 38})
        shuffleCenterChooseItem:setLayoutComponentEnabled(true)
        shuffleCenterChooseItem:setName("shuffleCenterChooseItem")
        shuffleCenterChooseItem:setTag(21)
        shuffleCenterChooseItem:setCascadeColorEnabled(true)
        shuffleCenterChooseItem:setCascadeOpacityEnabled(true)
        shuffleCenterChooseItem:setPosition(691.2000, 326.4000)
        layout = ccui.LayoutComponent:bindLayoutComponent(shuffleCenterChooseItem)
        layout:setPositionPercentXEnabled(true)
        layout:setPositionPercentYEnabled(true)
        layout:setPositionPercentX(0.9000)
        layout:setPositionPercentY(0.6000)
        layout:setPercentWidth(0.3906)
        layout:setPercentHeight(0.1103)
        layout:setSize({width = 300.0000, height = 60.0000})
        layout:setLeftMargin(541.2000)
        layout:setRightMargin(-73.2000)
        layout:setTopMargin(187.6000)
        layout:setBottomMargin(296.4000)
        menuPanel:addChild(shuffleCenterChooseItem)

        --Create shuffleBottomChooseItem
        shuffleBottomChooseItem = ccui.Button:create()
        shuffleBottomChooseItem:ignoreContentAdaptWithSize(false)
        shuffleBottomChooseItem:loadTextureNormal("Photos/Button/3DBUTTONSMALL_NORMAL.png",0)
        shuffleBottomChooseItem:loadTexturePressed("Photos/Button/3DBUTTONSMALL_SELECTED.png",0)
        shuffleBottomChooseItem:loadTextureDisabled("Default/Button_Disable.png",0)
        shuffleBottomChooseItem:setTitleFontName("fonts/STHUPO.TTF")
        shuffleBottomChooseItem:setTitleFontSize(36)
        shuffleBottomChooseItem:setTitleText(Ui_Shuffle_Button["Ui_Shuffle_Button_Bottom"])
        shuffleBottomChooseItem:setScale9Enabled(true)
        shuffleBottomChooseItem:setCapInsets({x = 15, y = 11, width = 270, height = 38})
        shuffleBottomChooseItem:setLayoutComponentEnabled(true)
        shuffleBottomChooseItem:setName("shuffleBottomChooseItem")
        shuffleBottomChooseItem:setTag(22)
        shuffleBottomChooseItem:setCascadeColorEnabled(true)
        shuffleBottomChooseItem:setCascadeOpacityEnabled(true)
        shuffleBottomChooseItem:setPosition(691.2000, 163.2000)
        layout = ccui.LayoutComponent:bindLayoutComponent(shuffleBottomChooseItem)
        layout:setPositionPercentXEnabled(true)
        layout:setPositionPercentYEnabled(true)
        layout:setPositionPercentX(0.9000)
        layout:setPositionPercentY(0.3000)
        layout:setPercentWidth(0.3906)
        layout:setPercentHeight(0.1103)
        layout:setSize({width = 300.0000, height = 60.0000})
        layout:setLeftMargin(541.2000)
        layout:setRightMargin(-73.2000)
        layout:setTopMargin(350.8000)
        layout:setBottomMargin(133.2000)
        menuPanel:addChild(shuffleBottomChooseItem)

        --Create shuffleEndItem
        shuffleEndItem = ccui.Button:create()
        shuffleEndItem:ignoreContentAdaptWithSize(false)
        shuffleEndItem:loadTextureNormal("Photos/Button/3DBUTTONSMALL_NORMAL.png",0)
        shuffleEndItem:loadTexturePressed("Photos/Button/3DBUTTONSMALL_SELECTED.png",0)
        shuffleEndItem:loadTextureDisabled("Default/Button_Disable.png",0)
        shuffleEndItem:setTitleFontName("fonts/STHUPO.TTF")
        shuffleEndItem:setTitleFontSize(36)
        shuffleEndItem:setTitleText(Ui_Shuffle_Button["Ui_Shuffle_Button_end"])
        shuffleEndItem:setScale9Enabled(true)
        shuffleEndItem:setCapInsets({x = 15, y = 11, width = 270, height = 38})
        shuffleEndItem:setLayoutComponentEnabled(true)
        shuffleEndItem:setName("shuffleEndItem")
        shuffleEndItem:setTag(23)
        shuffleEndItem:setCascadeColorEnabled(true)
        shuffleEndItem:setCascadeOpacityEnabled(true)
        shuffleEndItem:setPosition(384.0000, 54.4000)
        layout = ccui.LayoutComponent:bindLayoutComponent(shuffleEndItem)
        layout:setPositionPercentXEnabled(true)
        layout:setPositionPercentYEnabled(true)
        layout:setPositionPercentX(0.5000)
        layout:setPositionPercentY(0.1000)
        layout:setPercentWidth(0.3906)
        layout:setPercentHeight(0.1103)
        layout:setSize({width = 300.0000, height = 60.0000})
        layout:setLeftMargin(234.0000)
        layout:setRightMargin(234.0000)
        layout:setTopMargin(459.6000)
        layout:setBottomMargin(24.4000)
        menuPanel:addChild(shuffleEndItem)

        --Create insertMenuPanel
        insertMenuPanel = ccui.Layout:create()
        insertMenuPanel:ignoreContentAdaptWithSize(false)
        insertMenuPanel:setClippingEnabled(false)
        insertMenuPanel:setBackGroundColorType(1)
        insertMenuPanel:setBackGroundColor({r = 0, g = 0, b = 0})
        insertMenuPanel:setBackGroundColorOpacity(0)
        insertMenuPanel:setTouchEnabled(true);
        insertMenuPanel:setLayoutComponentEnabled(true)
        insertMenuPanel:setName("insertMenuPanel")
        insertMenuPanel:setTag(22)
        insertMenuPanel:setCascadeColorEnabled(true)
        insertMenuPanel:setCascadeOpacityEnabled(true)
        insertMenuPanel:setVisible(false)
        insertMenuPanel:setPosition(670.3104, 352.6208)
        layout = ccui.LayoutComponent:bindLayoutComponent(insertMenuPanel)
        layout:setPositionPercentXEnabled(true)
        layout:setPositionPercentYEnabled(true)
        layout:setPositionPercentX(0.85)
        layout:setPositionPercentY(0.65)
        layout:setPercentWidthEnabled(true)
        layout:setPercentHeightEnabled(true)
        layout:setPercentWidth(0.2500)
        layout:setPercentHeight(0.2000)
        layout:setSize({width = 192.0000, height = 108.8000})
        layout:setLeftMargin(670.3104)
        layout:setRightMargin(-94.3104)
        layout:setTopMargin(82.5792)
        layout:setBottomMargin(352.6208)
        menuPanel:addChild(insertMenuPanel)

        --Create shuffleTopInsertItem
        shuffleTopInsertItem = ccui.Button:create()
        shuffleTopInsertItem:ignoreContentAdaptWithSize(false)
        shuffleTopInsertItem:loadTextureNormal("Photos/Button/3DBUTTONLITTLESMALL_NORMAL.png",0)
        shuffleTopInsertItem:loadTexturePressed("Photos/Button/3DBUTTONLITTLESMALL_SELECTED.png",0)
        shuffleTopInsertItem:loadTextureDisabled("Default/Button_Disable.png",0)
        shuffleTopInsertItem:setTitleFontName("fonts/STHUPO.TTF")
        shuffleTopInsertItem:setTitleFontSize(24)
        shuffleTopInsertItem:setTitleText(Ui_Shuffle_Button["Ui_Shuffle_Button_Top"])
        shuffleTopInsertItem:setScale9Enabled(true)
        shuffleTopInsertItem:setCapInsets({x = 15, y = 11, width = 120, height = 8})
        shuffleTopInsertItem:setLayoutComponentEnabled(true)
        shuffleTopInsertItem:setName("shuffleTopInsertItem")
        shuffleTopInsertItem:setTag(23)
        shuffleTopInsertItem:setCascadeColorEnabled(true)
        shuffleTopInsertItem:setCascadeOpacityEnabled(true)
        shuffleTopInsertItem:setVisible(true)
        shuffleTopInsertItem:setPosition(96.0000, 92.4800)
        layout = ccui.LayoutComponent:bindLayoutComponent(shuffleTopInsertItem)
        layout:setPositionPercentXEnabled(true)
        layout:setPositionPercentYEnabled(true)
        layout:setPositionPercentX(0.5000)
        layout:setPositionPercentY(0.8500)
        layout:setPercentWidthEnabled(true)
        layout:setPercentHeightEnabled(true)
        layout:setPercentWidth(0.7813)
        layout:setPercentHeight(0.2757)
        layout:setSize({width = 150.0096, height = 29.9962})
        layout:setLeftMargin(20.9952)
        layout:setRightMargin(20.9952)
        layout:setTopMargin(1.3219)
        layout:setBottomMargin(77.4819)
        insertMenuPanel:addChild(shuffleTopInsertItem)

        --Create shuffleCenterInsertItem
        shuffleCenterInsertItem = ccui.Button:create()
        shuffleCenterInsertItem:ignoreContentAdaptWithSize(false)
        shuffleCenterInsertItem:loadTextureNormal("Photos/Button/3DBUTTONLITTLESMALL_NORMAL.png",0)
        shuffleCenterInsertItem:loadTexturePressed("Photos/Button/3DBUTTONLITTLESMALL_SELECTED.png",0)
        shuffleCenterInsertItem:loadTextureDisabled("Default/Button_Disable.png",0)
        shuffleCenterInsertItem:setTitleFontName("fonts/STHUPO.TTF")
        shuffleCenterInsertItem:setTitleFontSize(24)
        shuffleCenterInsertItem:setTitleText(Ui_Shuffle_Button["Ui_Shuffle_Button_Center"])
        shuffleCenterInsertItem:setScale9Enabled(true)
        shuffleCenterInsertItem:setCapInsets({x = 15, y = 11, width = 120, height = 8})
        shuffleCenterInsertItem:setLayoutComponentEnabled(true)
        shuffleCenterInsertItem:setName("shuffleCenterInsertItem")
        shuffleCenterInsertItem:setTag(26)
        shuffleCenterInsertItem:setCascadeColorEnabled(true)
        shuffleCenterInsertItem:setCascadeOpacityEnabled(true)
        shuffleCenterInsertItem:setVisible(true)
        shuffleCenterInsertItem:setPosition(96.0000, 54.4000)
        layout = ccui.LayoutComponent:bindLayoutComponent(shuffleCenterInsertItem)
        layout:setPositionPercentXEnabled(true)
        layout:setPositionPercentYEnabled(true)
        layout:setPositionPercentX(0.5000)
        layout:setPositionPercentY(0.5000)
        layout:setPercentWidthEnabled(true)
        layout:setPercentHeightEnabled(true)
        layout:setPercentWidth(0.7813)
        layout:setPercentHeight(0.2757)
        layout:setSize({width = 150.0096, height = 29.9962})
        layout:setLeftMargin(20.9952)
        layout:setRightMargin(20.9952)
        layout:setTopMargin(39.4019)
        layout:setBottomMargin(39.4019)
        insertMenuPanel:addChild(shuffleCenterInsertItem)

        --Create shuffleBottomInsertItem
        shuffleBottomInsertItem = ccui.Button:create()
        shuffleBottomInsertItem:ignoreContentAdaptWithSize(false)
        shuffleBottomInsertItem:loadTextureNormal("Photos/Button/3DBUTTONLITTLESMALL_NORMAL.png",0)
        shuffleBottomInsertItem:loadTexturePressed("Photos/Button/3DBUTTONLITTLESMALL_SELECTED.png",0)
        shuffleBottomInsertItem:loadTextureDisabled("Default/Button_Disable.png",0)
        shuffleBottomInsertItem:setTitleFontName("fonts/STHUPO.TTF")
        shuffleBottomInsertItem:setTitleFontSize(24)
        shuffleBottomInsertItem:setTitleText(Ui_Shuffle_Button["Ui_Shuffle_Button_Bottom"])
        shuffleBottomInsertItem:setScale9Enabled(true)
        shuffleBottomInsertItem:setCapInsets({x = 15, y = 11, width = 120, height = 8})
        shuffleBottomInsertItem:setLayoutComponentEnabled(true)
        shuffleBottomInsertItem:setName("shuffleBottomInsertItem")
        shuffleBottomInsertItem:setTag(27)
        shuffleBottomInsertItem:setCascadeColorEnabled(true)
        shuffleBottomInsertItem:setCascadeOpacityEnabled(true)
        shuffleBottomInsertItem:setVisible(true)
        shuffleBottomInsertItem:setPosition(96.0000, 16.3200)
        layout = ccui.LayoutComponent:bindLayoutComponent(shuffleBottomInsertItem)
        layout:setPositionPercentXEnabled(true)
        layout:setPositionPercentYEnabled(true)
        layout:setPositionPercentX(0.5000)
        layout:setPositionPercentY(0.1500)
        layout:setPercentWidthEnabled(true)
        layout:setPercentHeightEnabled(true)
        layout:setPercentWidth(0.7813)
        layout:setPercentHeight(0.2757)
        layout:setSize({width = 150.0096, height = 29.9962})
        layout:setLeftMargin(20.9952)
        layout:setRightMargin(20.9952)
        layout:setTopMargin(77.4819)
        layout:setBottomMargin(1.3219)
        insertMenuPanel:addChild(shuffleBottomInsertItem)
end

--退出APP button
    function exitMenuLayer()
        local function ExitApp()
            local targetPlatform = cc.Application:getInstance():getTargetPlatform()
            if cc.PLATFORM_OS_WINDOWS == targetPlatform then
                cclog("You pressed the close button. Windows Store Apps do not implement a close button.")
                return
            end

            cc.Director:getInstance():endToLua()

            if (cc.PLATFORM_OS_IPHONE == targetPlatform) or (cc.PLATFORM_OS_IPAD == targetPlatform) or (cc.PLATFORM_OS_MAC == targetPlatform) then
                exit(0)
            end

            cclog("app quit")

        end

        local ExitItem = cc.MenuItemImage:create("Photos/Button/CloseNormal.png", "Photos/Button/CloseSelected.png")
        ExitItem:setPosition(ORIGIN.x + WIN_SIZE.width - ExitItem:getContentSize().width/2, ORIGIN.y + ExitItem:getContentSize().height/2)
        ExitItem:registerScriptTapHandler(ExitApp)
        local Menu = cc.Menu:create(ExitItem)
        Menu:setPosition(0,0)
        Menu:addTo(root,UI_LAYERZORDER_MENU)

    end

--init
    createCocosStudioUI()
    exitMenuLayer()
end

--构造函数,在create中执行
function Shuffle2UI:ctor()
        initUI()
end

function Shuffle2UI:getMenuItem(args)
    if (args == "insertMenuPanel") then
        return insertMenuPanel
    elseif (args == "shuffleTopChooseItem") then
        return shuffleTopChooseItem
    elseif (args == "shuffleCenterChooseItem") then
        return shuffleCenterChooseItem
    elseif (args == "shuffleBottomChooseItem") then
        return shuffleBottomChooseItem
    elseif (args == "shuffleEndItem") then
        return shuffleEndItem
    elseif (args == "shuffleTopInsertItem") then
        return shuffleTopInsertItem
    elseif (args == "shuffleCenterInsertItem") then
        return shuffleCenterInsertItem
    elseif (args == "shuffleBottomInsertItem") then
        return shuffleBottomInsertItem
    end
end

cclog("Shuffle2UI==========================================================")
return Shuffle2UI