cc.FileUtils:getInstance():setPopupNotify(false)
cc.FileUtils:getInstance():addSearchPath("src/")
cc.FileUtils:getInstance():addSearchPath("res/")

require "cocos.init"
print("*********************AppMacros************")
function AppMacros()

--显示适配
SMALLRESOURCE = cc.size(480, 320)
MEDIUMRESOURCE = cc.size(1024, 768)
LARGERESOURCE = cc.size(2048, 1536)
VISIBLE_SIZE = cc.Director:getInstance():getVisibleSize()
ORIGIN = cc.Director:getInstance():getVisibleOrigin()
WIN_SIZE = cc.Director:getInstance():getWinSize()

--字体
TITLE_FONT_SIZE_LITTLESMALL = cc.Director:getInstance():getOpenGLView():getDesignResolutionSize().width / MEDIUMRESOURCE.width * 30
TITLE_FONT_SIZE_SMALL = cc.Director:getInstance():getOpenGLView():getDesignResolutionSize().width / MEDIUMRESOURCE.width * 36
TITLE_FONT_SIZE_MEDIUM = cc.Director:getInstance():getOpenGLView():getDesignResolutionSize().width / MEDIUMRESOURCE.width * 48
TITLE_FONT_SIZE_LARGE = cc.Director:getInstance():getOpenGLView():getDesignResolutionSize().width / MEDIUMRESOURCE.width * 60

--占卜
--DIVINE = 0                --问题 Begin.lua
LIFE = 100                --生活
ENTERPRISE = 101          --事业
LOVE = 102                --爱情

--Tarot
  --序号
  TAROT_FIRST = 200
  TAROT_LAST = 221
  --正逆位
  UPRIHT = 298
  DOWNRIGHT = 299

  --资源
   Tarot_Photo = {}
   Tarot_Photo[0] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/000FOOL.jpg"}
   Tarot_Photo[1] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/001MAGICIAN.jpg"}
   Tarot_Photo[2] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/002HIGHPRIESTESS.jpg"}
   Tarot_Photo[3] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/003EMPRESS.jpg"}
   Tarot_Photo[4] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/004EMPEROR.jpg"}
   Tarot_Photo[5] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/005HIGHPRIEST.jpg"}
   Tarot_Photo[6] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/006LOVERS.jpg"}
   Tarot_Photo[7] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/007CHARIOT.jpg"}
   Tarot_Photo[8] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/008STRENGTH.jpg"}
   Tarot_Photo[9] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/009HERMIT.jpg"}
   Tarot_Photo[10] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/010WHEELOFFORTUNE.jpg"}
   Tarot_Photo[11] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/011JUSTICE.jpg"}
   Tarot_Photo[12] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/012HANGEDMAN.jpg"}
   Tarot_Photo[13] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/013DEATH.jpg"}
   Tarot_Photo[14] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/014TEMPERANCE.jpg"}
   Tarot_Photo[15] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/015DEVIL.jpg"}
   Tarot_Photo[16] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/016TOWER.jpg"}
   Tarot_Photo[17] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/017STAR.jpg"}
   Tarot_Photo[18] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/018MOON.jpg"}
   Tarot_Photo[19] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/019SUN.jpg"}
   Tarot_Photo[20] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/020JUDGEMENT.jpg"}
   Tarot_Photo[21] = {["Tarot_Photo"] = "Photos/Tarot/TarotLarge/021WORLD.jpg"}

   Tarot_Content = {}
   Tarot_Content[0] = {   ["Tarot_Mean"] = "    The young man, dressed in gorgeous clothes and walking on the edge of a cliff,what is reflected in his eyes is his ideal country. He carries the rose (pure heart) in his left hand, and carries all his family's home with his right hand, wandering around. His face is full of wit and dreams. The puppy next to him reminded him not to keep pushing forward and stop to think about it. Realers say he is arrogant. Idealists think he has the spirit of adventure. As long as you still have dreams, you have to work hard to turn it into reality. What is the risk?Take a risk! Whatever you do, do it. The way to satisfaction is through spontaneous action, and long-term plan is the future.",
                          ["Tarot_Life_UpRight"] = "    Look forward to a good dream, a natural place, an aimless move, an attempt to challenge new things, go on and go around. A time of jumping out of the passing state, or a period of time to enjoy the present day. You will live in the present, and have a sense of close combination of life. Travel has unexpected gains, good health. Everything is full, and fun is in it.",
                          ["Tarot_Life_DownRight"] = "    Take risks, pursue possibilities, value dreams, ignore material losses, leave home and trust others too much.Worry about traveling and get sick because of an unstable life. Poor grasp of age is not to take action when opportunity comes, but to take action at inappropriate time.",
                          ["Tarot_Enterprise_UpRight"] = "    Passion for career or academic work, unexpected gains in a unique way, and curiosity as a result of strong interest in current studies. Grasp the key points, seek shortcuts, tend to a free working atmosphere, be suitable for artistic work or engage in freelance work. You have a free and free attitude in your career and maintain a relaxed and natural mood to meet the challenges ahead.",
                          ["Tarot_Enterprise_DownRight"] = "    You are overconfident and opinionated in your career. Even the advice of others can not give you any vigilance. Lost the most critical opportunity, so only get half the results with double the effort. Poor grasp of age is not to take action when opportunity comes, but to take action at inappropriate time.",
                          ["Tarot_Love_UpRight"] = "    Free love, easy to fall in love, romantic and colorful love, unique lovers, waiting for opportunities to communicate. You are about to start or have entered a simple and simple emotional life, not like glue, nor dull. Your partner, he (she) is an unsophisticated innocent person who likes the free life now and does not want to be influenced by rigid plans and arrangements.",
                          ["Tarot_Love_DownRight"] = "    Emotionally, it is almost persistent to weave too many illusory dreams, You can't communicate with your partner smoothly, your relationship is unstable, your emotions sometime is hot sometime is cold."
                      }

   Tarot_Content[1] = {   ["Tarot_Mean"] = "    The Mercury of the Rome mythology has a confident smile and bright eyes. The table has four elements of the universe: the life tree (fire), the sword (wind), the five awn star (soil), the Holy Grail (water), the infinity of the head, the snakes connected to the end of the waist, and the roses and the lilies under the feet. Pointing to the sky with his wand in his right hand, he pointed to the ground with his left hand. Acting is like asking for heaven's power and power to arouse magic. Look at this wizard. He seems to have unlimited power. He has a sword, a cup, a star and a stick on his table, but he holds a magic wand. What can he change from the nothingness? You are a magician, and you have the power to manipulate the universe! Success will be a great harvest, and failure is also between thoughts in a second.",
                          ["Tarot_Life_UpRight"] = "    This is an opportune time to start new things. The right time, the right opportunity, the right motivation, to make your effort return to the ticket price. It is a good time to start the action and realize the plan. Since you have made a good foundation for the plan, the new adventure can be achieved. Clear sense of direction and will power. Well, it greatly improves the possibility of success",
                          ["Tarot_Life_DownRight"] = "    You have a speculative mind, you are afraid of being hurt in your own protective layer, do not abide by some basic rules, do not hesitate to control the other way or even destroy your opponent to achieve your goal, so it will bring all kinds of mental, emotional or health problems. You have lost the right motivation, plan, enthusiasm, or pragmatism. To fulfill your heart's desire.",
                          ["Tarot_Enterprise_UpRight"] = "    You have good motivation, skilled skill, skill, broad mind and plenty of preparation in your career. Everything is in your plan. Grasp the opportunity to advance steadily and steadily. Carry out the will of yourself and use the power of nature to achieve ambition.",
                          ["Tarot_Enterprise_DownRight"] = "    In the wrong direction, knowledge is not enough. You have a speculative mind, you are afraid of being hurt in your own protective layer, do not abide by some basic rules, do not hesitate to control the other way or even destroy your opponent to achieve your purpose. You have lost the right motivation, plan, enthusiasm, or pragmatism. To fulfill your heart's desire.",
                          ["Tarot_Love_UpRight"] = "    Love is easy, a tacit partner, a new lover. The external environment has no effect on you, in the initiative, the active gender relationship.And perhaps one of the partners is inspirational, the other is down-to-earth, making these ideas concrete.",
                          ["Tarot_Love_DownRight"] = "    There is no progress in love and attention to the behavior of a partner. You have a speculative mind, you are afraid of being hurt in your own protective layer, do not abide by some basic rules, do not hesitate to control the other way or even destroy your opponent to achieve your goal, so it will bring all kinds of mental, emotional or health problems. You have lost the right motivation, plan, enthusiasm, or pragmatism. To fulfill your heart's desire."
                      }

   Tarot_Content[2] = {   ["Tarot_Mean"] = "    The holy priestess sat upright, with a curved moon beside her feet, with a scroll on her hand and a cross on her chest. There is a column on each side, which is the two pillars of the Jerusalem temple, Boaz and Jakin. There was a piece of cloth in the middle. The mantle covered a pool of water. Though she could not see it, she felt that it was there, but it did not fully understand its existence. Although the priestess held the scroll, she did not know the content. When she meets a man who can complement her negative energy, the man will know what it means, and she can tell him where the scroll came from.The holy priestess must use her intuition to understand what is hidden behind the pool of water behind her.",
                          ["Tarot_Life_UpRight"] = "    Develop the inner mystical potential, the prophecy that the future will change, deep thinking, keen insight and accurate intuition. You should trust your instincts, and you may not see some of them.Explore your heart for a time to sow the next stage of your life, or to digest what you are doing at the body level.",
                          ["Tarot_Life_DownRight"] = "    Ignorance, impulsiveness, lack of understanding. Perhaps you have passed a period of solitude and put your energy into the growth of your soul, and you have come back to life again to try your new ideas and understanding.",
                          ["Tarot_Enterprise_UpRight"] = "    It means that there is an accurate analysis in every step of the career, and careful use of high intuition to speculate about everything that will happen. The change around is also an important basis for predicting the future, and constantly revising the future.",
                          ["Tarot_Enterprise_DownRight"] = "    You can't continue to analyze the spirit in your career, start using other ways to determine the future direction, and try to find foreign aid and cooperation. This time you should go out and make new friends, because people you just know can help you introduce new possibilities and opportunities, and you may find new jobs.",
                          ["Tarot_Love_UpRight"] = "    A Platon love, a cold love affair. Emotionally, there is a tendency to be reserved and cautious. First, accept it passively, and then come to your own answer.Pursue and have a high level of spiritual love, have a good grasp of the development of emotions. A relationship with high spiritual or spiritual development, you two can learn, grow and develop together.",
                          ["Tarot_Love_DownRight"] = "    Emotionally indifferent, insensitive, and after a temporary solitude and introspection, it is possible to return to real life to find a partner again. This time you should go out and make new friends, because the people you just know can help you introduce new possibilities and opportunities, and you may find new partners."
                      }

   Tarot_Content[3] = {   ["Tarot_Mean"] = "    The beautiful queen wears a three level crown and sits gracefully on a comfortable chair.Surrounded by dense forests, there is a sense of carefree and easygoing.She sat on the magnificent cushion with a heart on her side. This is the sign of Venus.Surrounded by life, water brought vitality to the grass and trees, and the soil was full of wheat ears.It seems that she is willing to give you these fertile land and fruits, perfect love.We should be grateful.",
                          ["Tarot_Life_UpRight"] = "    Plentiful harvest and love means a plan to come true or a new stage, and a family harmony.A trip to the countryside, or rest for a while and return to the embrace of nature. By approaching nature, it's time for you to rebalance yourself.",
                          ["Tarot_Life_DownRight"] = "    Inactive, lack of ambition, loose living habits, unresolved things, can not see the results.Hedonism, perilous environment, and dissension with your family.",
                          ["Tarot_Enterprise_UpRight"] = "    Down-to-earth work will eventually lead to career achievements, and experience gained through hard work will help you get better on your way to success in the future. Your work is related to your home, or use your home as a base for work.",
                          ["Tarot_Enterprise_DownRight"] = "    Even if we are down-to-earth in our work, we will not be able to meet our requirements. Finding insufficient and trying to correct it",
                          ["Tarot_Love_UpRight"] = "    It is necessary to understand the integrity of a relationship between the two sexes, which requires practical efforts, to be satisfied and understood through emotion. The relationship between the sexes moves towards the next natural stage. you and your partner are close to life through feelings and joy, not through thought, in which there is more growth and vitality.",
                          ["Tarot_Love_DownRight"] = "    A bad relationship between men and women is too emotional to be idealized and can't tolerate flawed feelings. It may be difficult in the family or relationship between lovers. On the child's problem, it may mean infertility, abortion. Excessive reason can not show the emotional side."
                      }

   Tarot_Content[4] = {   ["Tarot_Mean"] = "    On the top of the throne sits the supreme emperor, who wears a crown studded with jewels and holds a mace symbolizing power and status. He is very experienced and dignified. Even though he is a king of a country, he still wears armor and is always ready to meet challenges for his country.He ruled the whole country with an unquestionable authority. He was the leader of the people, a symbol of male authority. However, he had a kindly heart after his majestic appearance. He was enthusiastic and willing to share his secret of success with those seeking advice: relying on the mind and the experience accumulated in the past struggle. His advice is worthy of your trust just like his upright personality.As the ruler of a country, it is the example of being a father. Otherwise, how to educate his people? But is the emperor who can dominate the country is happy?",
                          ["Tarot_Life_UpRight"] = "    Glory, power, victory, leadership, strong will, achievement of goals, father's responsibility, spiritual loneliness. Life is quite stable and orderly.",
                          ["Tarot_Life_DownRight"] = "    Naive weakness, dictatorship, indulgent capricious, ordinary, unconfident, insufficient action, weak will,be control, lack of self-discipline and withdrawal. More tolerant, and more able to show compassion.",
                          ["Tarot_Enterprise_UpRight"] = "    A career has achieved good results through self-discipline and down-to-earth effort, and a pragmatic attitude will make you at the top of your career longer. For success, it is time for you to take a pragmatic approach to life. Because of self-discipline and hard work, business is usually successful.",
                          ["Tarot_Enterprise_DownRight"] = "    The business will fail because of stubbornness and arbitrariness. The weak economic foundation can not succeed because of lack of self-discipline.",
                          ["Tarot_Love_UpRight"] = "    You are not very good at expressing feelings, though you have a good material foundation. You prefer to play the role of father in relationship between lovers. Giving is often something concrete, not emotion, because to you, giving is giving something concrete. So it feels a little depressed emotionally. There is great disparity in age between you. The dowry is rich. ",
                          ["Tarot_Love_DownRight"] = "    Emotionally, because of the lack of self - restraint, you are not single-minded and may have more than one partner. Lack of commitment to your partner or solid material foundation makes it difficult for you to get a real partner. Love is a reluctant, painful and unfruitless love. "
                      }

   Tarot_Content[5] = {   ["Tarot_Mean"] = "    The Pope sat on a magnificent chair, his right hand held to the sky, and his left hand held a treasure stick with a three cross. A red robe covered the white coat with a golden crown of three layers on his head. There were three cross patterns on the robe and a cross figure on the shoes. Two gold keys with cross patterns were placed in front of the seat. Two followers kneel in front of the foot. One of them has a red rose pattern on the clothes and the other has white lilies. The stone column behind it is dark gray, because the Church (or building) and its structure are less important for the pursuit of truth. The Pope used his right hand to transmit the energy from the sky. The Pope demonstrated the way for the believer to do so, and gave them directions. As long as they were followed, they could find a way to connect with God.",
                          ["Tarot_Life_UpRight"] = "    Be kind and generous. The advice given by a trustworthy person. A good object of discussion. Get spiritual satisfaction. Abide by the rules. Volunteers. Be trusted, valued, and confident. A correct understanding of the nature of things.",
                          ["Tarot_Life_DownRight"] = "    Wrong messages, malicious advice, aid interruption. The wish could not be reached. But the mind is broadened, the formation of new ideas and ideas, or rejection of some popular ideas. You are writing scripts for your life and living according to your understanding of life. You are responsible for your own spiritual development. Although the road may be rugged, it is usually worth it.",
                          ["Tarot_Enterprise_UpRight"] = "    There are too many external pressures on your work, and others have high expectations of you, which makes you feel bound. Looking for new ways of working, although it will face a lot of resistance, it turns out that it's worth it.",
                          ["Tarot_Enterprise_DownRight"] = "    More flexible attitude in the career, no longer rigid follow the old way, and be bold in innovation to form their own unique ideas. Live and work for your true ideas.",
                          ["Tarot_Love_UpRight"] = "    Love succumb to the pressure of others, only to change themselves blindly according to the requirements of the other, thinking that it is necessary to pay, but it is actually a forced choice. This relationship is a relationship that complies with the expectations of others. The partner in this relationship is hard to be faithful to himself and is hard to be faithful to their real needs in the relationship. Because they feel stressed when they adapt to others' expectations of them.",
                          ["Tarot_Love_DownRight"] = "    Emotionally, you began to face up to your true feelings and action. Although you will still listen to your lover's opinions, but will not accept it all. When you feel unable to accept the other's opinions, you will communicate with your lover in time to find ways to improve the relationship."
                      }

   Tarot_Content[6] = {   ["Tarot_Mean"] = "    A couple of men and women came together under the calling of angel and became lovers. Although the sun is shining and full of happiness, there are many tests waiting for them -- The tree of hope in the garden of Eden and the tree of forbidden fruit entrenched by venomous snakes. When a man may be so busy that he is busy in the material world for some substance, a woman will remind him that he has a spiritual goal and a higher meaning for survival. Perhaps when Adam of the garden of Eden take a bite of apple, he remembered his journey, his spiritual goals, and the work he was doing. It may become a despair or disillusionment. And before he takes responsibility for his own way of mind, he may also rebuke Eve for reminding him that he has to go on the road.",
                          ["Tarot_Life_UpRight"] = "    Love, popularity, interest, sensitivity, hopeful future, charm, and increase friends. You have grown from past experience, so you can move safely to a new stage.",
                          ["Tarot_Life_DownRight"] = "    Being unable to stand tempting, overindulgence, unpredictable, friendship become stranger, boredom, quarrel, rich magnificence dress, irresolute and hesitant. You are not ready for real life. You have expectations and hopes for growth, but you want to stay in your parents' protective layer forever to avoid danger and avoid responsibility. You haven't succeeded in completing your current state, so you still have to stay in old relationships.",
                          ["Tarot_Enterprise_UpRight"] = "    There will be a big choice in your career. It will relate to your future. A bright future, like-minded friends and partner. You have grown from past experience, so you can safely move towards a new stage.",
                          ["Tarot_Enterprise_DownRight"] = "    Your career always keeps a high level of vigilance, uncomfortable and unwilling to cooperate with you. You haven't succeeded in completing your current state, so you still stay in the old relationship better.",
                          ["Tarot_Love_UpRight"] = "    Matchmaking, emotional and physical desire for love, love will develop in a closer relationship to each other. The choice for the future, the time to decide the future, the romantic love, the preview of the appearance of love. You have grown from the past experience, so you can move safely to a new stage.",
                          ["Tarot_Love_DownRight"] = "    Emotionally naive, looking forward to growth and hope, but hoping to avoid danger, evade responsibility, and be indecisive. You have not successfully completed your current state, so you still stay in the old relationship better."
                      }

   Tarot_Content[7] = {   ["Tarot_Mean"] = "    A king's chariot to overcome obstacles and win. The victor stood on the chariot with a strong gesture to show his great achievements in the world. Holding a scepter in the right hand, there are two blue moon on the shoulders. The overcanopy of the chariot is covered with stars, while the belt shows the symbols of the twelve signs of the zodiac. The chariot partially stopped in the water and partially stopped on land. The winner manages two Sphinx, one black and one white. These forces require him to use his will power to control if he fails to fulfill his will, the two Sphinx may go in the opposite direction and tear his chariot in two. No matter how difficult and difficult the future may be, he must go on.",
                          ["Tarot_Life_UpRight"] = "    Work hard to succeed, win, overcome obstacles, action, self-reliance, try, self assertion, and lucky travel. Do not give up, because success is possible, as long as you can coordinate the conflict in the relationship. Success is due to persistence. It means that you are intellectually committed to fatalism, and persist in resisting old traditions. ",
                          ["Tarot_Life_DownRight"] = "    You are trapped by the backlog of emotions and need innovation to break through the old traditions. Sentimental unresolved feelings affect your perception of things. Don't indulge in the past, don't indulge in the old ways to deal with things, or indulge in the more and more higher emotion in your heart.",
                          ["Tarot_Enterprise_UpRight"] = "    You will show talent and fruitful in your career. Confident and rational you will make your customers more confident and willing to work together with you. Ambition, command, starting, go to win, quick decision, brilliant fruit, the spirit of opening up, defeat the opponent.",
                          ["Tarot_Enterprise_DownRight"] = "    If you give up what you have been doing in your career, the ending will be more perfect. Haste leads to failure, lack of money. You are trapped by the backlog of emotions and need innovation to break through the old traditions. Sentimental unresolved feelings affect your perception of things. Don't indulge in the past, don't indulge in the old ways to deal with things, or indulge in the more and more higher emotion in your heart.",
                          ["Tarot_Love_UpRight"] = "    Emotionally, you are trying to control your emotions and control it well, which makes your relationship develop more smoothly. The winner of love and passionate love. ",
                          ["Tarot_Love_DownRight"] = "    No interest, rejection, loss of trust, an evasive attitude to love. Emotional loss of direction, you have no past calm, which makes the other person have a distrust in the heart, perhaps you have to reflect on what you do. Sentimental unresolved feelings affect your perception of things. Don't indulge in the past, don't indulge in the old ways to deal with things, or indulge in the more and more higher emotion in your heart."
                      }

   Tarot_Content[8] = {   ["Tarot_Mean"] = "    The goddess of victory is bending her waist to caress a fierce lion, Although the lion could easily push her down, it was calm in her love and gentleness. At this time the sky was clear and cloudless, and a string of garlands around her waist. The top of the head represents an infinite sign, indicates that she is developing an endless source of energy. The lion easily accepted the command of her hands, because it felt that her power was behind her love. She had an inner strength or confidence that she could face the things that must be controlled by the chariot. She knew that lions were a source of energy, and that she needed some energy to tame it also.",
                          ["Tarot_Life_UpRight"] = "    A symbol of the inner strength is enough to face any difficulty. You have enough inner strength to face life. You have the ability to face life and difficult circumstances, or have the ability to change with hope, inner strength and courage. Courage does not mean that you have no fear, but even though you have fear, you are willing to commit and do something to someone or something.",
                          ["Tarot_Life_DownRight"] = "    Excessive doubt, indecision, lack of strength, patience, loss of confidence, loss of trust in others. Lose to the strong, fail to be tempted, give in to authority and common sense, give up without practice. Vanity, cowardice, no patience. Have the courage to not control life, but face it with love and sympathy.",
                          ["Tarot_Enterprise_UpRight"] = "    In your career, you constantly break through yourself, and your superiors and customers have full confidence in you, and achievements come one after another. Symbolizing the strength of the heart is enough to face any difficulties.",
                          ["Tarot_Enterprise_DownRight"] = "    The fear of the heart makes you flinch, and then meets the bottleneck of the cause, and feels lost. In a certain period, the security of the traditional cause or way of life seems attractive. Have the courage to not control life, but face it with love and sympathy.",
                          ["Tarot_Love_UpRight"] = "    In love, you will develop a truly intimate relationship. You put your heart into it and dedicate yourself to each other, talk to each other without any sense of distance. The people in this relationship can listen and talk to each other. Their actions come from inner strength, not from fear, and they can develop real intimacy, a strong love that can withstand the test.",
                          ["Tarot_Love_DownRight"] = "    In love, worry about personal gains and losses, loss of sober judgment. Unable to resist temptation, love can not last. Have the courage to not control life, but face it with love and sympathy."
                      }

   Tarot_Content[9] = {   ["Tarot_Mean"] = "    The hermit, in his long robe, stands in the snow, One hand was carrying a lamp with six star stars and the other was holding a stick. In the dark, alone and groping forward, there is no bright color, but which makes him see the faint things in life. The hermit tries to give up external temptation to achieve inner peace, and then to get truth through meditation in a quiet environment. In silence, you can only hear your inner voice, so that you can better understand your thoughts and find the ultimate goal of truly belonging to yourself.",
                          ["Tarot_Life_UpRight"] = "    Get out of your daily life so that the subconscious mind is active. Act first, and then think about the actions that are useful and what are wasteful. It will give you a clear understanding of what to do in the future. You go out by yourself, take a little risk, leave some ordinary things behind, and do what you really want to do. The light of a cage can only be seen in a short distance. No one can guarantee that it will be the right way. It needs to go through something alone by yourself.",
                          ["Tarot_Life_DownRight"] = "    It's time to stop and think about where you want to go and why you want to go that way. Perhaps you want to avoid loneliness and give in to the ordinary. Or because you are afraid of loneliness or fear that you may have to give up something, so you prefer to be comfortable rather than grow up.",
                          ["Tarot_Enterprise_UpRight"] = "    You retire in your golden age, and no one understands it, but you are resting for the coming golden age.",
                          ["Tarot_Enterprise_DownRight"] = "    Too much investment in your career has made you reluctant to face other things, and made breakthroughs in your career.",
                          ["Tarot_Love_UpRight"] = "    Emotionally, you will deeply think about your role and status in this relationship and explore the relationship between you. Pursue Platon style love, unrequited love. Take a little risk, leave some ordinary things behind, and do what you really want to do. The light of a cage can only be seen in a short distance. No one can guarantee that it will be the right way. It needs to go through something alone by yourself.",
                          ["Tarot_Love_DownRight"] = "    In emotional terms, use busy work to avoid the development of this relationship. Cold to your partner, because of fear of emotional development and at a critical moment to shrink back, making your lover cold."
                      }

   Tarot_Content[10] = {  ["Tarot_Mean"] = "    The card shows the wheel of fate. Above it is Steefan Kors, a symbol of an angel, and a devil beneath it, surrounded by goddesses, swans, and venomous snakes, which symbolize the various circumstances of fate.  Your destiny is like the wheel of fortune spinning constantly in the tarot, sometimes good and sometimes bad, which is a fair cycle. The wheel of fate may stop at the angle you like, which makes you have incredible luck, and it will stop at the angle you do not like, and you will be unlucky. Whether you like it or not, fate is so merciless, and life itself is constantly changing, which makes your life full of challenges and excitement.",
                          ["Tarot_Life_UpRight"] = "    There are new opportunities, conditions improve, problem solving, fortune is coming. The wheel of fortune is turning to the most sluggish moment of your life. Perhaps you are somewhat unacceptable, but if you look at it with your usual heart, this is undoubtedly the best time for you to grow up. You need to face it seriously. Change, go smoothly to success, and adapt to these changes.",
                          ["Tarot_Life_DownRight"] = "    Change, but facing difficulties, to adapt to these changes. Do not fight these events, often in vain. The universe contains greater power than every individual, so we have to work hard to understand what the change will teach us. The seasons are always replaced, and the more opportunities the life shows, the more The less you come, the better you should reflect on what you did in the past.",
                          ["Tarot_Enterprise_UpRight"] = "    A good time to come, to be wealthy and respect, to be flexible and to be promoted. Your career is improving.",
                          ["Tarot_Enterprise_DownRight"] = "    Change, but facing difficulties, to adapt to these changes. Do not fight these events, often in vain. The universe contains greater power than every individual, so we have to work hard to understand what the change will teach us. The seasons are always replaced, and the more opportunities the life shows, the more The less you come, the better you should reflect on what you did in the past.",
                          ["Tarot_Love_UpRight"] = "    Emotional setbacks are nearly to ruin you, but you are still working hard. Though you have countless thorns before you, it will be a smooth road to persist in the past. You will find that the previous effort has been meaningless, but now it has become the driving force for your progress. The previous effort paid off at last. The wheel of fortune is rotated by godness, so the storm and rain before you both will pass, and the relationship will enter a stable stage of development.",
                          ["Tarot_Love_DownRight"] = "    Lovelorn, love is short. Change, but facing difficulties, to adapt to these changes. Do not fight these events, often in vain. The universe contains greater power than every individual, so we have to work hard to understand what the change will teach us. The seasons are always replaced, and the more opportunities the life shows, the more The less you come, the better you should reflect on what you did in the past."
                      }

   Tarot_Content[11] = {  ["Tarot_Mean"] = "    The cool goddess of justice sits on a stone chair, with a sword of justice in his right hand, and an identification of the balance of good and evil in her left hand. By virtue of the two kinds of holy tools, the goddess can easily understand the origin and development of things, and let her face all the situation easily. At the same time, it also lets the world know the truth of the circulation of cause and effect. Warn people to be tolerant, abide by morality and uphold justice.",
                          ["Tarot_Life_UpRight"] = "    Justice means that things have reached its mission. Your past decisions or actions have led you to the present situation and you have got what you deserve. If you are honest with yourself, you must know that. Your future may be changed by your current decisions, actions, or understanding.",
                          ["Tarot_Life_DownRight"] = "    You will still be rewarded for your efforts, or you can still harvest your work, but this is unlikely to be a joyful harvest. You are not willing to track the causes of today's events, but always blame others for your predicament. If you are so lazy, you may lose the opportunity to have a better understanding of yourself and your life. This is not a time to expect others to teach you, but a time to save yourself.",
                          ["Tarot_Enterprise_UpRight"] = "    You don't have too much of a feeling in your career, just follow the previous plan. It may be a suggestion of job promotion, which is the result of a variety of decisions or past actions (that is, hard work brings rewards).",
                          ["Tarot_Enterprise_DownRight"] = "    A long period of depression has made you fall at the most critical moment of your career. You need to be carefully adjusted to move forward again.",
                          ["Tarot_Love_UpRight"] = "    You are quite satisfied with your emotional life and accept your choice of each other. It means that you have solved the dispute with your partner, or you have a completely honest and responsible attitude towards your partner and your relationship.",
                          ["Tarot_Love_DownRight"] = "    Emotionally, you have been patient, but you broke out this time and began to accuse the mistake of the other side. There will be great twists and turns in your love."
                      }

   Tarot_Content[12] = {  ["Tarot_Mean"] = "    The man was tied up, but he was quite calm, obedient and fortitude. His hands were placed behind his back, and a faint aura of angels appeared on his head. Although the other people thought this very painful, he had a quiet face, for he knew that he was sacrificed for others, even if his body was destroyed, but his spirit would remain forever. The hanged man knows that struggle is of no use, and in fact only makes him exhausted before he regains his freedom. He can use this time to reflect on the world at the moment, and then he can know the world again.",
                          ["Tarot_Life_UpRight"] = "    A bad situation is only a kind of practice for us. Bad luck will pass. The most important thing is to endure the evil luck before us, accept the arrangement of fate, reflect on the gains and losses of the past, and reserve power for the future rise again. Obedient to the environment, quietly waiting for the fate of arrangements, you are ready to give up what you have, so that you can do what you really should do in your life.",
                          ["Tarot_Life_DownRight"] = "    You can't get freedom that goes beyond social pressure. You will listen to what others expect from you, not the sound of your inner voice. You are constrained and desperate for freedom. Struggle is not right, because you can't get free before the right time comes. If you can use this time properly, so when life wants you to move forward, you don't need to spend more time thinking.",
                          ["Tarot_Enterprise_UpRight"] = "    Your career will have a brief pause, but you know the reasons for it, reconfirm your goals and make preparations for starting off.",
                          ["Tarot_Enterprise_DownRight"] = "    Career lack of vision, lost the goal of hard work. If you can use this time properly, so when life wants you to move forward, you don't need to spend more time thinking.",
                          ["Tarot_Love_UpRight"] = "    Emotionally, it takes time to reflect on your love, your sacrifice to love will greatly stimulate your lover and will also become a catalyst for your relationship development. You are pulling away from a relationship's daily life to reflect on your spiritual direction and the direction of relationship. Your partner may find it hard to get close to you in emotional or social terms now.",
                          ["Tarot_Love_DownRight"] = "    Emotionally, you don't have the idea to pay for the other person, and the other person's attitude towards you is still the same, which makes you want to escape. Struggle is not right, because you can't get free before the right time comes. If you can use this time properly, so when life wants you to move forward, you don't need to spend more time thinking."
                      }

   Tarot_Content[13] = {  ["Tarot_Mean"] = "    Death rides on the white horse, wearing his armor, showing his unstoppable strength. Someone has fallen down, someone accepts this cruel reality, someone tries to avoid it, and someone is doing a meaningless rebellion. The king refused to change, so he would be swept aside by the wave of life. The bishop stood facing death and supported his imminent changes with his spiritual beliefs. The young woman wants to accept change, but the ego resists it because it believes that if she does, she will be destroyed. She knelt before death, hoping that this change would pass her by. Only a child is totally innocent and can look at it calmly. The child is not afraid. He waits to change, even to give flowers.",
                          ["Tarot_Life_UpRight"] = "    A chapter in life is about to end. In the subconscious, you may be eager to change. The death card means change is going to happen. Do not resist the change, try to accept it, and your acceptance of this change will naturally happen.",
                          ["Tarot_Life_DownRight"] = "    You are extremely afraid of any form of death. You are addicted to the old habit. When you do not want to change, you must consume all power to keep still. Your fear of change makes you depressed, depressed or physically exhausted, because most of your energy is used to resist change. But they will come close to you in another direction, for example, from your heart, in dreams and emotions, or even physical symptoms, such as muscle tension or headache.",
                          ["Tarot_Enterprise_UpRight"] = "    In your career, you will give up some of the benefits you have got but get new opportunities for development.",
                          ["Tarot_Enterprise_DownRight"] = "    In your career, you are trying to make the best of both. Hope can happen miracles.",
                          ["Tarot_Love_UpRight"] = "    Emotionally, you will have a profound change that will start a new stage. Accept the fact that you will have a better journey. Leave, start again, have a deep gap, love the end. A profound change in the relationship between the two sexes, or your attitude to the relationship is about to change deeply. Or your attitude to the relationship is going to change deeply. It may be the end of a relationship, such as separation, or the end of a certain stage in the relationship, such as the birth of a baby.",
                          ["Tarot_Love_DownRight"] = "    Emotionally, the other person has accepted the change, but you are escaping from reality. The distance between you and you is getting bigger and bigger."
                      }

   Tarot_Content[14] = {  ["Tarot_Mean"] = "    With two holy grails in her hands, they represent 'matter' and 'spirit'. She is constantly pouring water from each other in the holy grails to balance the water of the two holy grails. It tells us that it is most important to control our desire when facing all kinds of temptations. It is not as happy and successful as the other cards. Feel plain beauty, after all, plain life is the real happiness.",
                          ["Tarot_Life_UpRight"] = "    Human ability is made up of knowledge and understanding of knowledge. We must have a purpose to do anything, let us mature through these things. Career development. Travel, teaching. The integration of action and emotion brings about the feeling of inner peace. The combination of reality and subconsciousness, the harmony between sensibility and reason.",
                          ["Tarot_Life_DownRight"] = "    The split between the higher self and the lower self leads to unrestrained behavior. We can see in some cultural or social views that money or material material is worth more than the spiritual level. In order to get sense of satisfaction, constantly seek the goal, but the result is only disappointment, and continue to set the next goal. Allow more changes to take place, and allow more things to stay away from your life, so that you can see farther or better.",
                          ["Tarot_Enterprise_UpRight"] = "    You are careful in your career, because your sense of reason makes your colleagues feel at ease.",
                          ["Tarot_Enterprise_DownRight"] = "    In your career, you are caught in a vicious circle that about like issuing an order in the morning and rescind it in the evening. You may as well follow the example of a fool who is willing to move forward and perhaps achieve greater success.",
                          ["Tarot_Love_UpRight"] = "    At present, your feelings are simple and calm. Everything is so pure and quiet, it is precisely because of communication that makes this emotional path so smooth. Favorable impression turns to affection, true love, deep love. A relationship that will lead to significant growth and learning. Strong senses of purpose are that every partner can act in a way which is faithful to himself, because they connect the subconscious (the pool water) and the real or tangible world (land).",
                          ["Tarot_Love_DownRight"] = "    Emotionally, although you are still trying to communicate with each other, you always feel no gain after each time. It is because of the distance between you will be greater and greater, and the coordination of love is not well."
                      }

   Tarot_Content[15] = {  ["Tarot_Mean"] = "    The demon looked at the chained slaves and made a grim smile. Although the slaves were tied up by the chains, they could get rid of the demon as long as they helped each other, but they had been blinded by the temptations of the demon, willing to be driven by him. Look at them carefully. They have grown their horns and tails like a devil. The hideous and terrible devil had such a beautiful voice that he tempted people to become his slaves with money and so-called safety. Under his control, people lost the ability to communicate with each other, and their hearts were full of completely naked desires. In pursuit of money to negate any other goal in life, people become selfish and greedy, but when the end of life, these substances no longer have any meaning.",
                          ["Tarot_Life_UpRight"] = "    Ambition dominates the mind. It is wrong to think that there is no choice. Indulge in material enjoyment and lack of spiritual support. A wrong idea - possessions of material possessions is real have everything. External interference makes people's impulses dominate reason, self spiritual demands disappear more and more, and begin to not be responsible for their actions, because you can put all the faults on the devil.",
                          ["Tarot_Life_DownRight"] = "    Find a way to break the bondage and find a new way. An attempt to break the chain that limits your freedom, whether it is physically or mentally free. This awakening may be more painful than to continue to ignore it, but it is a necessary stage, because if you have not experienced this injury, you may not be able to become complete again.",
                          ["Tarot_Enterprise_UpRight"] = "    You will gain considerable fame and wealth in your career. Your career is everything. Wealth is your goal.",
                          ["Tarot_Enterprise_DownRight"] = "    In career, reason begins to dominate desire, and to find goals that are really worth working for.",
                          ["Tarot_Love_UpRight"] = "    Emotionally, you begin to be bound by each other, but do not want to improve this relationship, and be willing to endure each other's implicating and dissatisfied. A relationship that begins with love turns into a bondage. Habit, formula and practicality have enslaved the heart of the person in the relationship. It may mean indulgence, or just for reasons of sex. It doesn't matter if you don't like your partner.",
                          ["Tarot_Love_DownRight"] = "    Emotionally, you start to try to communicate with your love, which makes your relationship stronger. Both love and hate relationship."
                      }

   Tarot_Content[16] = {  ["Tarot_Mean"] = "    A tower towering into the clouds was destroyed by lightning. Two people fell from the collapsed tower to the ground. The sudden and unforeseen changes are unacceptable, and the proud man can not be compared with the strength of nature, and the challenge of nature will only lead to the anger of God.",
                          ["Tarot_Life_UpRight"] = "    Your attitude to life has no way to support you again, you need to abandon these things to grow. If you are away from the rhythm or land of nature, you will risk the danger of disjointing with life. Life encourages you to keep its rhythm, and if you do not do it, it will not be able to support you completely again. When we are in trouble and unable to peacefully emancipate ourselves, life will liberate us by any means.",
                          ["Tarot_Life_DownRight"] = "   A feeling of obstruction or imprisoned continuity, because you do not allow all changes to happen. A feeling of obstruction or imprisoned continuity, because you do not allow all changes to happen. By stabilizing your actions, you can alleviate this pain, but it will also slow your growth. You resist the things you oppress, which may lead to another power, and another sudden, explosive powerful change. No matter how you resist change, it will happen sooner or later.",
                          ["Tarot_Enterprise_UpRight"] = "    The difficulty in career is obvious, and it is not the way to avoid it. Be brave to challenge, even though it looks strong. Your job or company at work will have a sudden change.",
                          ["Tarot_Enterprise_DownRight"] = "    There are signs of stability in your career. You should not blindly resist changes. This will only lead to greater changes. No matter how you resist, changes will eventually take place.",
                          ["Tarot_Love_UpRight"] = "    Sudden changes will cause you deep pain and accept changes that will enable you or both of you to walk better in your future life journey. A sudden change or disintegration occurred in the relationship between you. There is no way to continue to exist in a certain structure or mode. Sudden changes are made to enable you to grow again.",
                          ["Tarot_Love_DownRight"] = "    Emotionally, the feelings of both sides finally calm down, although there are some difficulties in communication, but there will not be much change. Maybe you can make some concessions and make your feelings more harmonious."
                      }

   Tarot_Content[17] = {  ["Tarot_Mean"] = "    The sky is clear, there are eight stars, each star has eight angles, clearly visible. In the light of the star of hope, Sirius, the goddess turns the holy water in the holy water bottle into the symbol subconscious pool, and the other is on the land of reality. She knows that people need hope so mach. So when the water is over, she is pouring another bottle again. So long as there is hope that people can have enough power to do a lot of things, so that hope is the source of human vitality. Let us dedicate all the love, though it is in the night but the stars of the sky give us direction and the bright future under the index of the stars.",
                          ["Tarot_Life_UpRight"] = "    A period of vacation or a period of time you can feel unhurried and peaceful. During this period, you know that you are the link between the subconscious and the tangible world. You choose something to show the subconscious, completely determined by you, so your best work or the most wonderful presentation is the most clear communication from the subconscious mind.",
                          ["Tarot_Life_DownRight"] = "    You are not in touch with the source of your subconscious energy at the moment, and may feel limited to life, or lose contact with the source of your creativity. You may feel that you need to rest for a while, leave a holiday, or have more freedom, but you need to be free from the mind, not the freedom of the body.",
                          ["Tarot_Enterprise_UpRight"] = "    When you get the energy of your career which is you hope to get, your future will be bright.",
                          ["Tarot_Enterprise_DownRight"] = "    In career, you should not rely entirely on others' giving, because you still have hope to burn in your heart, and only by yourself can you have the real motive for development.",
                          ["Tarot_Love_UpRight"] = "    Emotionally, you are confident in yourself. You are optimistic about the relationship between the two. Believe that you can take the initiative and strive to pursue the other. The cycle of cause and effect is the metaphor for this card. You are probably the one that is destined. In a relationship that provides support and freedom, you can live in your truth. Or do real yourself.",
                          ["Tarot_Love_DownRight"] = "    Emotionally, you can't trust each other and feel unable to commit yourself to each other. Maybe if you step back, you can calm down and find out the way to solve the problem, because the answer is in your heart."
                      }

   Tarot_Content[18] = {  ["Tarot_Mean"] = "    In the moonlight, the lobster crawled out of the water and moved to the moon goddess. It was to choose the right one of the two towers in the distance, because the tower was the only way to meet the moon goddess. The wolf and the hound on the shore were attracted by the moon goddess as well, and were temporarily unaware of the near close lobster. The challenge here is to walk along the edge of the pool without fear of being knocked down by the wolf and the hound. The moon is a bridge between the spirit and the world. It is a sign of change that the moon wins and the moon loses. When the full moon appears, people know that it will lose immediately. The uneasiness in the heart arises spontaneously. The bigger the moon is, the closer it is to becoming smaller. When people are worried about the unhappiness when they are happy, people can not have any slack.",
                          ["Tarot_Life_UpRight"] = "    Dreams and dreams reach the intuition of your conscious mind. Powerful dreams are trying to tell you something. Listen to your dreams, and you will find the answers you are looking for. Perhaps in the sober moments, you can easily recall those dreams. You may feel tired after your normal sleep, because a strong dream interferes with your sleep pattern.",
                          ["Tarot_Life_DownRight"] = "    Those things that have not been solved have come to you again. It is time to face these internal challenges, not to retreat into the security field of the tangible world. It can also remind you that the same pool contains your fears, and your strength and the solution to the problem also.",
                          ["Tarot_Enterprise_UpRight"] = "    You may be somewhat unhappy in your career, hoping to bring all your inner strength into full play, so you begin to want the evening time.",
                          ["Tarot_Enterprise_DownRight"] = "    In your career, you begin to shrink from external pressure and have doubts about your established goals.",
                          ["Tarot_Love_UpRight"] = "    Emotionally, you are very sensitive to fear of being hurt. Despite the commitment of a partner, you are still indecisive and even the idea of escaping. In everyday life everything is perfectly harmonious, but there are something undiscussed, recognized or unsolved in the dark. You wish to listen to your dreams or subconscious, perhaps you can find out what really happened in the depths of your heart.",
                          ["Tarot_Love_DownRight"] = "    Emotionally, the problems between you are beginning to emerge. Although there are some pain, as long as you face the difficulties together, the problem will be solved by half."
                      }

   Tarot_Content[19] = {  ["Tarot_Mean"] = "    The sun symbolizes knowledge and vitality. A child on a horse is singing the vitality of the sun, accepting the energy given to him by the sun. The sun is so powerful that it gives life to all things in the world, its light so warm, all life is moved. Its strength is full of positive, full of hope and ideal, any darkness can not resist its light. The sun gives you 'vitality', it is the power of hope and ideal, without any external interference and internal confrontation, even if the inner dark side wants to disturb you, but in the light of the sun, they will disappear immediately.",
                          ["Tarot_Life_UpRight"] = "    You feel joy and inner peace, and the universe is a place full of fun and creativity. The sun is the full manifestation of freedom. It liberate you from the daily limits of the conscious mind into a state of openness, awakening and freedom. It is an inner freedom that can bring freedom of flesh. The sun shows joy, peace, happiness and creative attitude towards life, and deeply appreciate the beauty of life.",
                          ["Tarot_Life_DownRight"] = "    You have a competitive attitude towards life and creativity. This is based on the fear of insufficient - fear of insufficient support, fear of opportunity or lack of love. It may be a fundamental fear that the world will not support your efforts. You still have some fears to be overcome.",
                          ["Tarot_Enterprise_UpRight"] = "    There will be good people in your career, and there will be better opportunities for development.",
                          ["Tarot_Enterprise_DownRight"] = "    The competition is too eager to scare all the competitors, but it also makes the partners feel afraid. Maybe you should relax. It may be that you have to stand out in sales or creative jobs, and you have to go through great competition.",
                          ["Tarot_Love_UpRight"] = "    Emotionally, you have come out of the rough road of emotion, ahead of the smooth path of singing and happiness, and you will begin to plan your future life.",
                          ["Tarot_Love_DownRight"] = "    Emotionally, there are some minor changes in love, and you begin to care about each other's attitude and your own efforts. These doubts may not be necessary."
                      }

   Tarot_Content[20] = {  ["Tarot_Mean"] = "    The angels blew the horn on the last judgment, so that the dead who heard the music were redeemed, while people rose from their tombs to rejoice. The horn of the angel can awaken the feelings of all people, even the repentant sinners have the hope of arriving in heaven. The horn blew by the angel symbolizes the death of old ideas. People are embracing the new world under the call of music. A flag with a red cross pattern on its white bottom is flying. Every man, woman, and child is looking up, because it is their way to return to god or the home of the creator. Every man, woman, and child is looking up, because it is their way to return to God or the home of the creator. In the beginning of the new world, you will find yourself not alone, and many friends learn with you. Though you have never met before, the Templar Angel helps you to help each other, which makes your life more enjoyable.",
                          ["Tarot_Life_UpRight"] = "    You can see yourself clearly and the time of life. It will make you feel great joy or panic about how to start and what you have. The harvest is very close. You can face your reward with your integrity and honesty. Now you judge yourself, and If you do not get what you want, there is no excuse for it, because what you harvest is the product of your efforts.",
                          ["Tarot_Life_DownRight"] = "    You will initiate a call from the heart. Perhaps your reason and logic are persuading you not to give up everything you have for something what is not clear or invisible. Every time you refuse or delay the call, the sense of emptiness deepens again. The harvest time has arrived. You must be responsible for your previous decisions, as the end of a chapter in life.",
                          ["Tarot_Enterprise_UpRight"] = "    In career, you surpass yourself and succeed on the basis of past efforts.",
                          ["Tarot_Enterprise_DownRight"] = "    There is no clear judgement in career, trying to fill spiritual emptiness with material.",
                          ["Tarot_Love_UpRight"] = "    Emotionally, both sides are studying and growing seriously, although there is little change on the surface, but the internal changes are great. Look at your harvest in this relationship, and you can know which behavior has produced these results. All of your current things are not accidental.",
                          ["Tarot_Love_DownRight"] = "    Emotionally, you are constantly reminiscent of the good old days and unwilling to face up to the problems before you. Your relationship is already appear united outwardly but divided at heart."
                      }

   Tarot_Content[21] = {  ["Tarot_Mean"] = "    You have reached the door of success, the goddess of success let you wait, she will let you enter the door of success, it is only a matter of time. Around the door of success is the happiness and sadness you have experienced, the success and failure, It is necessary to recall the past times before reaching the promised land. All things can be done. All dreams can come true. There is no impossible thing to get. As long as you work hard, you will have the corresponding harvest. As long as you have a grateful heart, you will be able to find bliss and happiness in the beautiful world you build for yourself.",
                          ["Tarot_Life_UpRight"] = "    Completion, success, perfection, a joy from the heart, lasting success. The establishment of a new era of permanence and success.",
                          ["Tarot_Life_DownRight"] = "    Failure to complete, fail, prepare insufficient, obscure judgement, and lack of opportunity.",
                          ["Tarot_Enterprise_UpRight"] = "    Because of hard work in career, it pays a lot of rewards. It has a lifelong goal and a mission. It is a great success and content.",
                          ["Tarot_Enterprise_DownRight"] = "    There are huge obstacles on the way to your career. You are lassitude, give up halfway and you lose the power of challenge.",
                          ["Tarot_Love_UpRight"] = "    Emotionally, you continue to have a good relationship with each other's commitments. It shows that you are in a common relationship. You and your partner can grow, develop, and live within the scope of your consent. This relationship is quite powerful. If it is in the past, it may mean a partner living in another place, or when you travel to another place, you may meet someone.",
                          ["Tarot_Love_DownRight"] = "    Emotionally, you no longer value commitment, but blindly accept each other. You'd better communicate with each other, and don't let the pain continue to twist you."
                      }
end
print("*********************AppMacros************")